global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'sentinel-api'
    static_configs:
      - targets: ['sentinel-api:8080']

  - job_name: 'sentinel-consumer'
    static_configs:
      - targets: ['sentinel-consumer:2112']
